code

equ	trap_Print							-1
equ	trap_Error							-2
equ	trap_Milliseconds					-3
equ	trap_Cvar_Register					-4
equ	trap_Cvar_Update					-5
equ	trap_Cvar_Set						-6
equ trap_Cvar_VariableStringBuffer		-7
equ	trap_Argc							-8
equ	trap_Argv							-9
equ	trap_Args							-10
equ	trap_FS_FOpenFile					-11
equ	trap_FS_Read						-12
equ	trap_FS_Write						-13 
equ	trap_FS_FCloseFile					-14
equ	trap_SendConsoleCommand				-15
equ	trap_AddCommand						-16
equ	trap_SendClientCommand				-17
equ	trap_UpdateScreen					-18
equ	trap_CM_LoadMap						-19
equ	trap_CM_NumInlineModels				-20
equ	trap_CM_InlineModel					-21
equ	trap_CM_LoadModel					-22
equ	trap_CM_TempBoxModel				-23
equ	trap_CM_PointContents				-24
equ	trap_CM_TransformedPointContents	-25
equ	trap_CM_BoxTrace					-26
equ	trap_CM_TransformedBoxTrace			-27
equ	trap_CM_MarkFragments				-28
equ	trap_S_StartSound					-29
equ	trap_S_StartLocalSound				-30
equ	trap_S_ClearLoopingSounds			-31
equ	trap_S_AddLoopingSound				-32
equ	trap_S_UpdateEntityPosition			-33
equ	trap_S_Respatialize					-34
equ	trap_S_RegisterSound				-35
equ	trap_S_StartBackgroundTrack			-36
equ	trap_R_LoadWorldMap					-37
equ	trap_R_RegisterModel				-38
equ	trap_R_RegisterSkin					-39
equ	trap_R_RegisterShader				-40
equ	trap_R_ClearScene					-41
equ	trap_R_AddRefEntityToScene			-42
equ	trap_R_AddPolyToScene				-43
equ	trap_R_AddLightToScene				-44
equ	trap_R_RenderScene					-45
equ	trap_R_SetColor						-46
equ	trap_R_DrawStretchPic				-47
equ	trap_R_ModelBounds					-48
equ	trap_R_LerpTag						-49
equ	trap_GetGlconfig					-50
equ	trap_GetGameState					-51
equ	trap_GetCurrentSnapshotNumber		-52
equ	trap_GetSnapshot					-53
equ	trap_GetServerCommand				-54
equ	trap_GetCurrentCmdNumber			-55
equ	trap_GetUserCmd						-56
equ	trap_SetUserCmdValue				-57
equ	trap_R_RegisterShaderNoMip			-58
equ	trap_MemoryRemaining				-59
equ trap_R_RegisterFont					-60
equ trap_Key_IsDown						-61
equ trap_Key_GetCatcher					-62
equ trap_Key_SetCatcher					-63
equ trap_Key_GetKey						-64
equ trap_PC_AddGlobalDefine				-65
equ	trap_PC_LoadSource					-66
equ trap_PC_FreeSource					-67
equ trap_PC_ReadToken					-68
equ trap_PC_SourceFileAndLine			-69
equ trap_S_StopBackgroundTrack			-70
equ trap_RealTime						-71
equ trap_SnapVector						-72
equ trap_RemoveCommand					-73
equ trap_R_LightForPoint				-74
equ trap_CIN_PlayCinematic				-75
equ trap_CIN_StopCinematic				-76
equ trap_CIN_RunCinematic 				-77
equ trap_CIN_DrawCinematic				-78
equ trap_CIN_SetExtents					-79
equ trap_R_RemapShader					-80
equ	trap_S_AddRealLoopingSound			-81
equ trap_S_StopLoopingSound				-82
equ trap_CM_TempCapsuleModel			-83
equ trap_CM_CapsuleTrace				-84
equ trap_CM_TransformedCapsuleTrace		-85
equ trap_R_AddAdditiveLightToScene		-86
equ trap_GetEntityToken					-87
equ	trap_R_AddPolysToScene				-88
equ trap_R_inPVS						-89
equ trap_FS_Seek			-90

equ	memset						-101
equ	memcpy						-102
equ	strncpy						-103
equ	sin							-104
equ	cos							-105
equ	atan2						-106
equ	sqrt						-107
equ floor						-108
equ	ceil						-109
equ	testPrintInt				-110
equ	testPrintFloat				-111
equ acos						-112
equ trap_R_LFX_ParticleEffect	-113
equ trap_R_GetViewPosition		-114

; oax engine extensions (oax_public.h): number N is equ -(N+1)
equ trap_OAX_DebugSet			-1001
equ trap_OAX_BSPXRead			-1002
equ trap_OAX_R_SetViewFog		-1013
equ trap_OAX_S_SetReverb		-1021
equ trap_OAX_CG_GuiLoad			-1031
equ trap_OAX_CG_GuiFree			-1032
equ trap_OAX_CG_GuiSetState		-1033
equ trap_OAX_CG_GuiActivate		-1034
equ trap_OAX_R_AddRefEntityExt	-1035
equ trap_OAX_CG_GuiTrace		-1036
equ trap_OAX_CG_GuiCursor		-1037
equ trap_OAX_R_UpdateLight		-1051
equ trap_OAX_R_SetLightStyle	-1011

; physics (bg_oax_phys.h): block 1200-1299, the same numbers in game and cgame
equ trap_Phys_WorldCreate                 -1201
equ trap_Phys_WorldDestroy                -1202
equ trap_Phys_WorldStep                   -1203
equ trap_Phys_WorldAddBSP                 -1204
equ trap_Phys_WorldAddHeightField         -1205
equ trap_Phys_WorldSetGravity             -1206
equ trap_Phys_WorldStats                  -1207
equ trap_Phys_WorldHash                   -1208
equ trap_Phys_WorldExplode                -1209
equ trap_Phys_WorldContactEvents          -1210
equ trap_Phys_BodyCreate                  -1211
equ trap_Phys_BodyDestroy                 -1212
equ trap_Phys_BodyAddShape                -1213
equ trap_Phys_BodySetTransform            -1214
equ trap_Phys_BodySetVelocity             -1215
equ trap_Phys_BodyApply                   -1216
equ trap_Phys_BodySetTarget               -1217
equ trap_Phys_BodySetParam                -1218
equ trap_Phys_BodyGetState                -1219
equ trap_Phys_BodyGetStates               -1220
equ trap_Phys_BodyFromBSPModel            -1221
equ trap_Phys_BodyGetMass                 -1222
equ trap_Phys_RagdollCreate               -1223
equ trap_Phys_JointCreate                 -1231
equ trap_Phys_JointDestroy                -1232
equ trap_Phys_JointSetParam               -1233
equ trap_Phys_JointGetParam               -1234
equ trap_Phys_Raycast                     -1241
equ trap_Phys_RaycastBatch                -1242
equ trap_Phys_Shapecast                   -1243
equ trap_Phys_Overlap                     -1244
equ trap_Phys_R_ModelSkeleton             -1251
equ trap_Phys_R_LerpSkeleton              -1252
equ trap_Phys_R_AddSkeletalEntity         -1253
equ trap_Phys_R_ModelFrames               -1254
equ trap_OAX_R_RegisterFx		-1014
equ trap_OAX_R_AddFx			-1015
equ trap_OAX_R_AddDecal			-1016
equ trap_OAX_R_AddTrail			-1017
equ trap_OAX_R_ClearDecals		-1018
