name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build the QVMs
        run: make
      - name: Upload the QVMs
        uses: actions/upload-artifact@v4
        with:
          name: oax-qvms-${{ matrix.os }}
          path: build/release-*/oax/vm/*.qvm
